### ISSUE TITLE
Bug: Tabs Component Required More Than 1 Tab

### ISSUE THREAD

**Issue by jwdotjs** [knledg/react-blur-admin#33]
If you create a Tabs component and put only one tab inside it, it will through an invariant:

```javascript
invariant.js:38 Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {title, children}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Tabs`.
```

Reproducable Sample Code
```javascript
<Tabs align='top'>
          <Tab title='All'>
             hi
          </Tab>
</Tabs>
```

We should handle this one of two ways:

1. Update the tabs component to allow 1 or many tabs
2. Throw an error if we have less than 2 tabs, saying that 2 or more tabs are required. 

I think option 1 would be better if possible, there may be situations where tabs are dynamically generated and the user may only have one.

**Comment by AFogarty72** [comment]
<img width="1448" alt="screen shot 2016-06-15 at 11 26 34 am" src="https://cloud.githubusercontent.com/assets/16338229/16092304/1c5b83c6-32ec-11e6-8aa5-05c3a0ffce09.png">
